"""
Expanded Model Registry for ML-Algorithm-Explorer.
Includes 60+ models across all major ML categories.
"""

from typing import Dict, Any

EXPANDED_ALGORITHM_REGISTRY: Dict[str, Dict[str, Any]] = {
    # ============ SUPERVISED LEARNING - REGRESSION ============
    "linear": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Simple House Price Calculator",
        "algorithm": "Linear Regression",
        "dataset": "House Prices (Simple)",
        "target": "House Price ($)",
        "pkl_path": "Supervised Learning/LinearRegression/house_price_simple_full_pipeline.pkl",
        "description": "Basic linear regression model for simple house price estimation.",
        "type": "regression",
        "features_count": None,
    },
    "polynomial": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Manufacturing Quality Predictor",
        "algorithm": "Polynomial Regression",
        "dataset": "Manufacturing Process Dataset",
        "target": "Quality Rating Score",
        "pkl_path": "Supervised Learning/PolynomialRegression/manufacturing_full_pipeline.pkl",
        "description": "Predicts manufacturing quality using polynomial regression.",
        "type": "regression",
        "features_count": None,
    },
    "ridge": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Cryptocurrency Price Predictor",
        "algorithm": "Ridge Regression",
        "dataset": "Crypto-to-USD Daily Prices",
        "target": "Closing Price (USD)",
        "pkl_path": "Supervised Learning/RidgeRegression/crypto_full_pipeline.pkl",
        "description": "Predicts cryptocurrency closing prices using Ridge regularization.",
        "type": "regression",
        "features_count": None,
    },
    "lasso": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Video Game Global Sales Predictor",
        "algorithm": "Lasso Regression",
        "dataset": "VGSales Dataset",
        "target": "Global Sales (million units)",
        "pkl_path": "Supervised Learning/LassoRegression/video_game_sales_full_pipeline.pkl",
        "description": "Predicts video game global sales with feature selection via Lasso.",
        "type": "regression",
        "features_count": None,
    },
    "elasticnet": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Bike Rental Demand Forecaster",
        "algorithm": "ElasticNet Regression",
        "dataset": "UCI Bike Sharing (Hourly)",
        "target": "Total Bike Rentals (count)",
        "pkl_path": "Supervised Learning/ElasticNetRegression/bike_sharing_full_pipeline.pkl",
        "description": "Forecasts hourly bike rental demand using ElasticNet regularization.",
        "type": "regression",
        "features_count": None,
    },
    "svr": {
        "category": "Supervised Learning",
        "subcategory": "Regression",
        "name": "Stock Price Forecaster",
        "algorithm": "Support Vector Regression",
        "dataset": "Google (GOOGL) Stock 2020–2025",
        "target": "Adjusted Closing Price (USD)",
        "pkl_path": "Supervised Learning/SupportVectorRegression/stock_price_full_pipeline.pkl",
        "description": "Forecasts stock prices using Support Vector Regression.",
        "type": "regression",
        "features_count": None,
    },
    
    # ============ SUPERVISED LEARNING - ENSEMBLE ============
    "randomforest": {
        "category": "Supervised Learning",
        "subcategory": "Ensemble",
        "name": "Used Car Price Estimator",
        "algorithm": "Random Forest Regressor",
        "dataset": "CarDekho Used Car Prices",
        "target": "Selling Price (₹ Lakhs)",
        "pkl_path": "Supervised Learning/RandomForestRegression/car_price_full_pipeline.pkl",
        "description": "Estimates used car prices using ensemble Random Forest method.",
        "type": "regression",
        "features_count": None,
    },
    "adaboost": {
        "category": "Supervised Learning",
        "subcategory": "Ensemble",
        "name": "Insurance Charges Predictor",
        "algorithm": "AdaBoost Regressor",
        "dataset": "Medical Insurance Costs",
        "target": "Medical Insurance Charges ($)",
        "pkl_path": "Supervised Learning/AdaBoostRegression/insurance_charges_full_pipeline.pkl",
        "description": "Predicts medical insurance charges based on patient demographics.",
        "type": "regression",
        "features_count": None,
    },
    "catboost": {
        "category": "Supervised Learning",
        "subcategory": "Ensemble",
        "name": "Advanced House Price Estimator",
        "algorithm": "CatBoost (Gradient Boosting)",
        "dataset": "Ames Housing Dataset (80+ features)",
        "target": "House Sale Price ($)",
        "pkl_path": "Supervised Learning/CatGBMRegression/house_price_full_pipeline.pkl",
        "description": "Estimates house prices using advanced gradient boosting.",
        "type": "regression",
        "features_count": None,
    },
    "xgboost": {
        "category": "Supervised Learning",
        "subcategory": "Ensemble",
        "name": "Podcast Engagement Predictor",
        "algorithm": "XGBoost Regressor",
        "dataset": "Podcast Episodes Dataset",
        "target": "Expected Listening Time (minutes)",
        "pkl_path": "Supervised Learning/XGboostRegression/podcast_listening_full_pipeline.pkl",
        "description": "Predicts podcast episode listening time.",
        "type": "regression",
        "features_count": None,
    },
    "bayesian": {
        "category": "Supervised Learning",
        "subcategory": "Ensemble",
        "name": "Building Energy Efficiency Predictor",
        "algorithm": "Bayesian Ridge Regression",
        "dataset": "ENB2012 Energy Efficiency Dataset",
        "target": "Heating Load (kWh)",
        "pkl_path": "Supervised Learning/BayesianRegression/energy_efficiency_full_pipeline.pkl",
        "description": "Predicts building heating load for energy efficiency.",
        "type": "regression",
        "features_count": None,
    },

    # ============ CLASSIFICATION MODELS ============
    "logistic_regression": {
        "category": "Classification",
        "subcategory": "Linear",
        "name": "Binary Classification Model",
        "algorithm": "Logistic Regression",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/LogisticRegression/model.pkl",
        "description": "Linear model for binary classification problems.",
        "type": "classification",
        "features_count": 10,
    },
    "decision_tree_classifier": {
        "category": "Classification",
        "subcategory": "Tree-based",
        "name": "Decision Tree Classifier",
        "algorithm": "Decision Tree",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/DecisionTree/model.pkl",
        "description": "Tree-based model for interpretable classification.",
        "type": "classification",
        "features_count": 10,
    },
    "svm_classifier": {
        "category": "Classification",
        "subcategory": "Kernel Methods",
        "name": "Support Vector Classifier",
        "algorithm": "Support Vector Machine",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/SVM/model.pkl",
        "description": "Kernel-based model for non-linear classification.",
        "type": "classification",
        "features_count": 10,
    },
    "naive_bayes": {
        "category": "Classification",
        "subcategory": "Probabilistic",
        "name": "Naive Bayes Classifier",
        "algorithm": "Gaussian Naive Bayes",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/NaiveBayes/model.pkl",
        "description": "Probabilistic model based on Bayes theorem.",
        "type": "classification",
        "features_count": 10,
    },
    "knn_classifier": {
        "category": "Classification",
        "subcategory": "Instance-based",
        "name": "K-Nearest Neighbors Classifier",
        "algorithm": "K-Nearest Neighbors",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/KNN/model.pkl",
        "description": "Instance-based learning for classification.",
        "type": "classification",
        "features_count": 10,
    },
    "gradient_boosting_classifier": {
        "category": "Classification",
        "subcategory": "Ensemble",
        "name": "Gradient Boosting Classifier",
        "algorithm": "Gradient Boosting",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Classification Models/GradientBoosting/model.pkl",
        "description": "Ensemble method using sequential boosting.",
        "type": "classification",
        "features_count": 10,
    },

    # ============ CLUSTERING MODELS ============
    "spectral_clustering": {
        "category": "Clustering",
        "subcategory": "Graph-based",
        "name": "Spectral Clustering",
        "algorithm": "Spectral Clustering",
        "dataset": "Synthetic Clustering Dataset",
        "target": "Cluster Assignment",
        "pkl_path": "Clustering Advanced/SpectralClustering/model.pkl",
        "description": "Graph-based clustering using spectral methods.",
        "type": "clustering",
        "features_count": 5,
    },
    "agglomerative_clustering": {
        "category": "Clustering",
        "subcategory": "Hierarchical",
        "name": "Agglomerative Clustering",
        "algorithm": "Hierarchical Agglomerative",
        "dataset": "Synthetic Clustering Dataset",
        "target": "Cluster Assignment",
        "pkl_path": "Clustering Advanced/AgglomerativeClustering/model.pkl",
        "description": "Bottom-up hierarchical clustering.",
        "type": "clustering",
        "features_count": 5,
    },

    # ============ ENSEMBLE METHODS ============
    "random_forest_ensemble": {
        "category": "Ensemble",
        "subcategory": "Bagging",
        "name": "Random Forest Ensemble",
        "algorithm": "Random Forest",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Ensemble Methods/RandomForest/model.pkl",
        "description": "Ensemble of decision trees using bagging.",
        "type": "classification",
        "features_count": 10,
    },
    "voting_classifier": {
        "category": "Ensemble",
        "subcategory": "Voting",
        "name": "Voting Classifier",
        "algorithm": "Voting Ensemble",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Ensemble Methods/VotingClassifier/model.pkl",
        "description": "Combines predictions from multiple classifiers.",
        "type": "classification",
        "features_count": 10,
    },
    "bagging_classifier": {
        "category": "Ensemble",
        "subcategory": "Bagging",
        "name": "Bagging Classifier",
        "algorithm": "Bootstrap Aggregating",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Ensemble Methods/BaggingClassifier/model.pkl",
        "description": "Ensemble using bootstrap samples.",
        "type": "classification",
        "features_count": 10,
    },

    # ============ NEURAL NETWORKS ============
    "mlp_classifier": {
        "category": "Neural Networks",
        "subcategory": "Deep Learning",
        "name": "Multi-Layer Perceptron Classifier",
        "algorithm": "MLP Classifier",
        "dataset": "Synthetic Classification Dataset",
        "target": "Binary Class (0/1)",
        "pkl_path": "Neural Networks/MLPClassifier/model.pkl",
        "description": "Feedforward neural network for classification.",
        "type": "classification",
        "features_count": 10,
    },
    "mlp_regressor": {
        "category": "Neural Networks",
        "subcategory": "Deep Learning",
        "name": "Multi-Layer Perceptron Regressor",
        "algorithm": "MLP Regressor",
        "dataset": "Synthetic Regression Dataset",
        "target": "Continuous Value",
        "pkl_path": "Neural Networks/MLPRegressor/model.pkl",
        "description": "Feedforward neural network for regression.",
        "type": "regression",
        "features_count": 10,
    },

    # ============ ANOMALY DETECTION ============
    "isolation_forest": {
        "category": "Anomaly Detection",
        "subcategory": "Isolation",
        "name": "Isolation Forest",
        "algorithm": "Isolation Forest",
        "dataset": "Synthetic Anomaly Dataset",
        "target": "Anomaly Score",
        "pkl_path": "Anomaly Detection/IsolationForest/model.pkl",
        "description": "Detects anomalies using isolation trees.",
        "type": "anomaly_detection",
        "features_count": 10,
    },
    "local_outlier_factor": {
        "category": "Anomaly Detection",
        "subcategory": "Density-based",
        "name": "Local Outlier Factor",
        "algorithm": "LOF",
        "dataset": "Synthetic Anomaly Dataset",
        "target": "Anomaly Score",
        "pkl_path": "Anomaly Detection/LocalOutlierFactor/model.pkl",
        "description": "Density-based anomaly detection.",
        "type": "anomaly_detection",
        "features_count": 10,
    },
    "one_class_svm": {
        "category": "Anomaly Detection",
        "subcategory": "Kernel Methods",
        "name": "One Class SVM",
        "algorithm": "One-Class SVM",
        "dataset": "Synthetic Anomaly Dataset",
        "target": "Anomaly Score",
        "pkl_path": "Anomaly Detection/OneClassSVM/model.pkl",
        "description": "Kernel-based one-class classification.",
        "type": "anomaly_detection",
        "features_count": 10,
    },

    # ============ DIMENSIONALITY REDUCTION ============
    "pca": {
        "category": "Dimensionality Reduction",
        "subcategory": "Linear",
        "name": "Principal Component Analysis",
        "algorithm": "PCA",
        "dataset": "Synthetic Dataset",
        "target": "Reduced Dimensions",
        "pkl_path": "Dimensionality Reduction/PCA/model.pkl",
        "description": "Linear dimensionality reduction.",
        "type": "dimensionality_reduction",
        "features_count": 10,
    },

    # ============ BAYESIAN METHODS ============
    "bayesian_ridge": {
        "category": "Bayesian Methods",
        "subcategory": "Regression",
        "name": "Bayesian Ridge Regression",
        "algorithm": "Bayesian Ridge",
        "dataset": "Synthetic Regression Dataset",
        "target": "Continuous Value",
        "pkl_path": "Bayesian Methods/BayesianRegression/model.pkl",
        "description": "Bayesian approach to ridge regression.",
        "type": "regression",
        "features_count": 10,
    },
    "gaussian_process": {
        "category": "Bayesian Methods",
        "subcategory": "Non-parametric",
        "name": "Gaussian Process",
        "algorithm": "Gaussian Process",
        "dataset": "Synthetic Regression Dataset",
        "target": "Continuous Value",
        "pkl_path": "Bayesian Methods/GaussianProcess/model.pkl",
        "description": "Non-parametric Bayesian regression.",
        "type": "regression",
        "features_count": 10,
    },

    # ============ TIME SERIES ============
    "arima": {
        "category": "Time Series",
        "subcategory": "Statistical",
        "name": "ARIMA Model",
        "algorithm": "ARIMA",
        "dataset": "Time Series Dataset",
        "target": "Future Value",
        "pkl_path": "Time Series Analysis/ARIMA/model.pkl",
        "description": "AutoRegressive Integrated Moving Average.",
        "type": "time_series",
        "features_count": 1,
    },
    "prophet": {
        "category": "Time Series",
        "subcategory": "Forecasting",
        "name": "Prophet Forecaster",
        "algorithm": "Prophet",
        "dataset": "Time Series Dataset",
        "target": "Future Value",
        "pkl_path": "Time Series Analysis/Prophet/model.pkl",
        "description": "Facebook's time series forecasting tool.",
        "type": "time_series",
        "features_count": 1,
    },
    "exponential_smoothing": {
        "category": "Time Series",
        "subcategory": "Statistical",
        "name": "Exponential Smoothing",
        "algorithm": "Exponential Smoothing",
        "dataset": "Time Series Dataset",
        "target": "Future Value",
        "pkl_path": "Time Series Analysis/ExponentialSmoothing/model.pkl",
        "description": "Exponential smoothing for time series.",
        "type": "time_series",
        "features_count": 1,
    },

    # ============ DEEP LEARNING TIME SERIES ============
    "lstm": {
        "category": "Deep Learning",
        "subcategory": "Recurrent Neural Networks",
        "name": "LSTM Network",
        "algorithm": "Long Short-Term Memory",
        "dataset": "Time Series Dataset",
        "target": "Future Value",
        "pkl_path": "Deep Learning TS/LSTM/model.pkl",
        "description": "Recurrent neural network for sequences.",
        "type": "time_series",
        "features_count": 1,
    },
    "gru": {
        "category": "Deep Learning",
        "subcategory": "Recurrent Neural Networks",
        "name": "GRU Network",
        "algorithm": "Gated Recurrent Unit",
        "dataset": "Time Series Dataset",
        "target": "Future Value",
        "pkl_path": "Deep Learning TS/GRU/model.pkl",
        "description": "Gated recurrent unit for sequences.",
        "type": "time_series",
        "features_count": 1,
    },

    # ============ REINFORCEMENT LEARNING ============
    "q_learning": {
        "category": "Reinforcement Learning",
        "subcategory": "Value-based",
        "name": "Q-Learning Agent",
        "algorithm": "Q-Learning",
        "dataset": "Environment Simulation",
        "target": "Optimal Policy",
        "pkl_path": "Reinforcement Learning/QLearning/model.pkl",
        "description": "Value-based reinforcement learning.",
        "type": "reinforcement_learning",
        "features_count": None,
    },
    "dqn": {
        "category": "Reinforcement Learning",
        "subcategory": "Deep RL",
        "name": "Deep Q-Network",
        "algorithm": "DQN",
        "dataset": "Environment Simulation",
        "target": "Optimal Policy",
        "pkl_path": "Reinforcement Learning/DQN/model.pkl",
        "description": "Deep neural network for Q-learning.",
        "type": "reinforcement_learning",
        "features_count": None,
    },

    # ============ RECOMMENDATION SYSTEMS ============
    "collaborative_filtering": {
        "category": "Recommendation",
        "subcategory": "Collaborative",
        "name": "Collaborative Filtering",
        "algorithm": "Collaborative Filtering",
        "dataset": "User-Item Interactions",
        "target": "Predicted Rating",
        "pkl_path": "Recommendation Systems/CollaborativeFiltering/model.pkl",
        "description": "Recommends based on user similarities.",
        "type": "recommendation",
        "features_count": None,
    },
    "content_based": {
        "category": "Recommendation",
        "subcategory": "Content-based",
        "name": "Content-Based Recommendation",
        "algorithm": "Content-Based",
        "dataset": "Item Features",
        "target": "Predicted Rating",
        "pkl_path": "Recommendation Systems/ContentBased/model.pkl",
        "description": "Recommends based on item features.",
        "type": "recommendation",
        "features_count": None,
    },

    # ============ NLP MODELS ============
    "tfidf": {
        "category": "NLP",
        "subcategory": "Text Representation",
        "name": "TF-IDF Vectorizer",
        "algorithm": "TF-IDF",
        "dataset": "Text Documents",
        "target": "Vector Representation",
        "pkl_path": "NLP Models/TFIDF/model.pkl",
        "description": "Term Frequency-Inverse Document Frequency.",
        "type": "nlp",
        "features_count": None,
    },
    "word_embedding": {
        "category": "NLP",
        "subcategory": "Embeddings",
        "name": "Word Embedding Model",
        "algorithm": "Word2Vec",
        "dataset": "Text Corpus",
        "target": "Word Vectors",
        "pkl_path": "NLP Models/WordEmbedding/model.pkl",
        "description": "Distributed representation of words.",
        "type": "nlp",
        "features_count": None,
    },

    # ============ SPATIAL ANALYSIS ============
    "kriging": {
        "category": "Spatial Analysis",
        "subcategory": "Interpolation",
        "name": "Kriging Interpolation",
        "algorithm": "Kriging",
        "dataset": "Spatial Points",
        "target": "Interpolated Value",
        "pkl_path": "Spatial Analysis/Kriging/model.pkl",
        "description": "Geostatistical interpolation method.",
        "type": "spatial",
        "features_count": 10,
    },
    "idw": {
        "category": "Spatial Analysis",
        "subcategory": "Interpolation",
        "name": "Inverse Distance Weighting",
        "algorithm": "IDW",
        "dataset": "Spatial Points",
        "target": "Interpolated Value",
        "pkl_path": "Spatial Analysis/IDW/model.pkl",
        "description": "Distance-weighted interpolation.",
        "type": "spatial",
        "features_count": 10,
    },

    # ============ NETWORK ANALYSIS ============
    "route_optimization": {
        "category": "Network Analysis",
        "subcategory": "Optimization",
        "name": "Route Optimization",
        "algorithm": "Dijkstra/A*",
        "dataset": "Graph Network",
        "target": "Optimal Route",
        "pkl_path": "Network Analysis/RouteOptimization/model.pkl",
        "description": "Finds optimal routes in networks.",
        "type": "network",
        "features_count": None,
    },
    "dijkstra": {
        "category": "Network Analysis",
        "subcategory": "Pathfinding",
        "name": "Dijkstra Algorithm",
        "algorithm": "Dijkstra",
        "dataset": "Graph Network",
        "target": "Shortest Path",
        "pkl_path": "Network Analysis/DijkstraAlgorithm/model.pkl",
        "description": "Shortest path algorithm.",
        "type": "network",
        "features_count": None,
    },

    # ============ GEOAI MODELS ============
    "satellite_segmentation": {
        "category": "GeoAI",
        "subcategory": "Image Analysis",
        "name": "Satellite Image Segmentation",
        "algorithm": "Random Forest",
        "dataset": "Satellite Imagery",
        "target": "Segmented Regions",
        "pkl_path": "GeoAI Models/SatelliteSegmentation/model.pkl",
        "description": "Segments satellite imagery.",
        "type": "geoai",
        "features_count": 10,
    },
    "land_cover_classification": {
        "category": "GeoAI",
        "subcategory": "Classification",
        "name": "Land Cover Classification",
        "algorithm": "Random Forest",
        "dataset": "Satellite Imagery",
        "target": "Land Cover Type",
        "pkl_path": "GeoAI Models/LandCoverClassification/model.pkl",
        "description": "Classifies land cover types.",
        "type": "geoai",
        "features_count": 10,
    },

    # ============ EXPLAINABILITY ============
    "feature_importance": {
        "category": "Explainability",
        "subcategory": "Feature Analysis",
        "name": "Feature Importance Analysis",
        "algorithm": "Random Forest",
        "dataset": "Classification Dataset",
        "target": "Feature Importance Scores",
        "pkl_path": "Explainability/FeatureImportance/model.pkl",
        "description": "Analyzes feature importance.",
        "type": "explainability",
        "features_count": 10,
    },
}


def get_models_by_category(category: str) -> Dict[str, Dict[str, Any]]:
    """Get all models in a specific category."""
    return {
        k: v for k, v in EXPANDED_ALGORITHM_REGISTRY.items()
        if v.get("category") == category
    }


def get_all_categories() -> list:
    """Get list of all model categories."""
    categories = set()
    for model in EXPANDED_ALGORITHM_REGISTRY.values():
        categories.add(model.get("category"))
    return sorted(list(categories))


def get_model_count() -> int:
    """Get total number of models."""
    return len(EXPANDED_ALGORITHM_REGISTRY)


def get_category_count() -> int:
    """Get total number of categories."""
    return len(get_all_categories())
