import { ActivitySquare, LayoutDashboard, Headphones } from 'lucide-react';

export const MODELS = {
  adaboost: {
    id: 'adaboost',
    name: 'Insurance Charges Engine',
    algorithm: 'AdaBoost Regressor',
    icon: ActivitySquare,
    colorClass: 'adaboost-icon',
    description: 'Predict patient medical insurance costs based on demographic and personal health features using an ensemble learning approach.',
    endpoint: 'adaboost',
    features: [
      { name: 'age', type: 'number', label: 'Age', default: 30 },
      { name: 'bmi', type: 'number', label: 'BMI (Body Mass Index)', default: 25.5 },
      { name: 'children', type: 'number', label: 'Number of Children', default: 1 },
      { name: 'sex', type: 'select', label: 'Sex', options: ['male', 'female'], default: 'male' },
      { name: 'smoker', type: 'select', label: 'Smoker', options: ['yes', 'no'], default: 'no' },
      { name: 'region', type: 'select', label: 'Region', options: ['southwest', 'southeast', 'northwest', 'northeast'], default: 'southwest' }
    ]
  },
  catboost: {
    id: 'catboost',
    name: 'Real Estate Valuation Model',
    algorithm: 'CatGBM Regressor',
    icon: LayoutDashboard,
    colorClass: 'catboost-icon',
    description: 'Estimate property values accurately using Categorical Gradient Boosting over 80+ complex architectural and location features.',
    endpoint: 'catboost',
    features: [
      { name: 'MSSubClass', type: 'number', label: 'MSSubClass', default: 0 },
      { name: 'MSZoning', type: 'number', label: 'MSZoning', default: 0 },
      { name: 'LotFrontage', type: 'number', label: 'LotFrontage', default: 0 },
      { name: 'LotArea', type: 'number', label: 'LotArea', default: 0 },
      { name: 'Street', type: 'number', label: 'Street', default: 0 },
      { name: 'Alley', type: 'number', label: 'Alley', default: 0 },
      { name: 'LotShape', type: 'number', label: 'LotShape', default: 0 },
      { name: 'LandContour', type: 'number', label: 'LandContour', default: 0 },
      { name: 'Utilities', type: 'number', label: 'Utilities', default: 0 },
      { name: 'LotConfig', type: 'number', label: 'LotConfig', default: 0 },
      { name: 'LandSlope', type: 'number', label: 'LandSlope', default: 0 },
      { name: 'Neighborhood', type: 'number', label: 'Neighborhood', default: 0 },
      { name: 'Condition1', type: 'number', label: 'Condition1', default: 0 },
      { name: 'Condition2', type: 'number', label: 'Condition2', default: 0 },
      { name: 'BldgType', type: 'number', label: 'BldgType', default: 0 },
      { name: 'HouseStyle', type: 'number', label: 'HouseStyle', default: 0 },
      { name: 'OverallQual', type: 'number', label: 'OverallQual', default: 0 },
      { name: 'OverallCond', type: 'number', label: 'OverallCond', default: 0 },
      { name: 'YearBuilt', type: 'number', label: 'YearBuilt', default: 0 },
      { name: 'YearRemodAdd', type: 'number', label: 'YearRemodAdd', default: 0 },
      { name: 'RoofStyle', type: 'number', label: 'RoofStyle', default: 0 },
      { name: 'RoofMatl', type: 'number', label: 'RoofMatl', default: 0 },
      { name: 'Exterior1st', type: 'number', label: 'Exterior1st', default: 0 },
      { name: 'Exterior2nd', type: 'number', label: 'Exterior2nd', default: 0 },
      { name: 'MasVnrType', type: 'number', label: 'MasVnrType', default: 0 },
      { name: 'MasVnrArea', type: 'number', label: 'MasVnrArea', default: 0 },
      { name: 'ExterQual', type: 'number', label: 'ExterQual', default: 0 },
      { name: 'ExterCond', type: 'number', label: 'ExterCond', default: 0 },
      { name: 'Foundation', type: 'number', label: 'Foundation', default: 0 },
      { name: 'BsmtQual', type: 'number', label: 'BsmtQual', default: 0 },
      { name: 'BsmtCond', type: 'number', label: 'BsmtCond', default: 0 },
      { name: 'BsmtExposure', type: 'number', label: 'BsmtExposure', default: 0 },
      { name: 'BsmtFinType1', type: 'number', label: 'BsmtFinType1', default: 0 },
      { name: 'BsmtFinSF1', type: 'number', label: 'BsmtFinSF1', default: 0 },
      { name: 'BsmtFinType2', type: 'number', label: 'BsmtFinType2', default: 0 },
      { name: 'BsmtFinSF2', type: 'number', label: 'BsmtFinSF2', default: 0 },
      { name: 'BsmtUnfSF', type: 'number', label: 'BsmtUnfSF', default: 0 },
      { name: 'TotalBsmtSF', type: 'number', label: 'TotalBsmtSF', default: 0 },
      { name: 'Heating', type: 'number', label: 'Heating', default: 0 },
      { name: 'HeatingQC', type: 'number', label: 'HeatingQC', default: 0 },
      { name: 'CentralAir', type: 'number', label: 'CentralAir', default: 0 },
      { name: 'Electrical', type: 'number', label: 'Electrical', default: 0 },
      { name: '1stFlrSF', type: 'number', label: '1stFlrSF', default: 0 },
      { name: '2ndFlrSF', type: 'number', label: '2ndFlrSF', default: 0 },
      { name: 'LowQualFinSF', type: 'number', label: 'LowQualFinSF', default: 0 },
      { name: 'GrLivArea', type: 'number', label: 'GrLivArea', default: 0 },
      { name: 'BsmtFullBath', type: 'number', label: 'BsmtFullBath', default: 0 },
      { name: 'BsmtHalfBath', type: 'number', label: 'BsmtHalfBath', default: 0 },
      { name: 'FullBath', type: 'number', label: 'FullBath', default: 0 },
      { name: 'HalfBath', type: 'number', label: 'HalfBath', default: 0 },
      { name: 'BedroomAbvGr', type: 'number', label: 'BedroomAbvGr', default: 0 },
      { name: 'KitchenAbvGr', type: 'number', label: 'KitchenAbvGr', default: 0 },
      { name: 'KitchenQual', type: 'number', label: 'KitchenQual', default: 0 },
      { name: 'TotRmsAbvGrd', type: 'number', label: 'TotRmsAbvGrd', default: 0 },
      { name: 'Functional', type: 'number', label: 'Functional', default: 0 },
      { name: 'Fireplaces', type: 'number', label: 'Fireplaces', default: 0 },
      { name: 'FireplaceQu', type: 'number', label: 'FireplaceQu', default: 0 },
      { name: 'GarageType', type: 'number', label: 'GarageType', default: 0 },
      { name: 'GarageYrBlt', type: 'number', label: 'GarageYrBlt', default: 0 },
      { name: 'GarageFinish', type: 'number', label: 'GarageFinish', default: 0 },
      { name: 'GarageCars', type: 'number', label: 'GarageCars', default: 0 },
      { name: 'GarageArea', type: 'number', label: 'GarageArea', default: 0 },
      { name: 'GarageQual', type: 'number', label: 'GarageQual', default: 0 },
      { name: 'GarageCond', type: 'number', label: 'GarageCond', default: 0 },
      { name: 'PavedDrive', type: 'number', label: 'PavedDrive', default: 0 },
      { name: 'WoodDeckSF', type: 'number', label: 'WoodDeckSF', default: 0 },
      { name: 'OpenPorchSF', type: 'number', label: 'OpenPorchSF', default: 0 },
      { name: 'EnclosedPorch', type: 'number', label: 'EnclosedPorch', default: 0 },
      { name: '3SsnPorch', type: 'number', label: '3SsnPorch', default: 0 },
      { name: 'ScreenPorch', type: 'number', label: 'ScreenPorch', default: 0 },
      { name: 'PoolArea', type: 'number', label: 'PoolArea', default: 0 },
      { name: 'PoolQC', type: 'number', label: 'PoolQC', default: 0 },
      { name: 'Fence', type: 'number', label: 'Fence', default: 0 },
      { name: 'MiscFeature', type: 'number', label: 'MiscFeature', default: 0 },
      { name: 'MiscVal', type: 'number', label: 'MiscVal', default: 0 },
      { name: 'MoSold', type: 'number', label: 'MoSold', default: 0 },
      { name: 'YrSold', type: 'number', label: 'YrSold', default: 0 },
      { name: 'SaleType', type: 'number', label: 'SaleType', default: 0 },
      { name: 'SaleCondition', type: 'number', label: 'SaleCondition', default: 0 },
      { name: 'MSZoning', type: 'select', label: 'MSZoning', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Street', type: 'select', label: 'Street', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Alley', type: 'select', label: 'Alley', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'LotShape', type: 'select', label: 'LotShape', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'LandContour', type: 'select', label: 'LandContour', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Utilities', type: 'select', label: 'Utilities', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'LotConfig', type: 'select', label: 'LotConfig', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'LandSlope', type: 'select', label: 'LandSlope', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Neighborhood', type: 'select', label: 'Neighborhood', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Condition1', type: 'select', label: 'Condition1', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Condition2', type: 'select', label: 'Condition2', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BldgType', type: 'select', label: 'BldgType', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'HouseStyle', type: 'select', label: 'HouseStyle', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'RoofStyle', type: 'select', label: 'RoofStyle', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'RoofMatl', type: 'select', label: 'RoofMatl', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Exterior1st', type: 'select', label: 'Exterior1st', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Exterior2nd', type: 'select', label: 'Exterior2nd', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'MasVnrType', type: 'select', label: 'MasVnrType', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'ExterQual', type: 'select', label: 'ExterQual', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'ExterCond', type: 'select', label: 'ExterCond', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Foundation', type: 'select', label: 'Foundation', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BsmtQual', type: 'select', label: 'BsmtQual', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BsmtCond', type: 'select', label: 'BsmtCond', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BsmtExposure', type: 'select', label: 'BsmtExposure', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BsmtFinType1', type: 'select', label: 'BsmtFinType1', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'BsmtFinType2', type: 'select', label: 'BsmtFinType2', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Heating', type: 'select', label: 'Heating', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'HeatingQC', type: 'select', label: 'HeatingQC', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'CentralAir', type: 'select', label: 'CentralAir', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Electrical', type: 'select', label: 'Electrical', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'KitchenQual', type: 'select', label: 'KitchenQual', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Functional', type: 'select', label: 'Functional', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'FireplaceQu', type: 'select', label: 'FireplaceQu', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'GarageType', type: 'select', label: 'GarageType', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'GarageFinish', type: 'select', label: 'GarageFinish', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'GarageQual', type: 'select', label: 'GarageQual', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'GarageCond', type: 'select', label: 'GarageCond', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'PavedDrive', type: 'select', label: 'PavedDrive', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'PoolQC', type: 'select', label: 'PoolQC', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'Fence', type: 'select', label: 'Fence', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'MiscFeature', type: 'select', label: 'MiscFeature', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'SaleType', type: 'select', label: 'SaleType', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' },
      { name: 'SaleCondition', type: 'select', label: 'SaleCondition', options: ['Unknown', 'Typ', 'Gd', 'TA', 'Fa', 'Ex', 'Po'], default: 'Unknown' }
    ]
  },
  xgboost: {
    id: 'xgboost',
    name: 'Podcast Engagement Predictor',
    algorithm: 'XGBoost Regressor',
    icon: Headphones,
    colorClass: 'xgboost-icon',
    description: 'Forecast the expected listening time of a podcast episode based on host popularity, genre, and sentiment analysis.',
    endpoint: 'xgboost',
    features: [
      { name: 'Episode_Length_minutes', type: 'number', label: 'Episode Length (min)', default: 45 },
      { name: 'Host_Popularity_percentage', type: 'number', label: 'Host Popularity (%)', default: 85 },
      { name: 'Guest_Popularity_percentage', type: 'number', label: 'Guest Popularity (%)', default: 70 },
      { name: 'Number_of_Ads', type: 'number', label: 'Number of Ads', default: 2 },
      { name: 'Genre', type: 'select', label: 'Genre', options: ['Technology', 'Comedy', 'True Crime', 'News', 'Education', 'Sports'], default: 'Technology' },
      { name: 'Publication_Day', type: 'select', label: 'Publication Day', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], default: 'Wednesday' },
      { name: 'Publication_Time', type: 'select', label: 'Time of Day', options: ['Morning', 'Afternoon', 'Evening', 'Night'], default: 'Morning' },
      { name: 'Episode_Sentiment', type: 'select', label: 'Sentiment', options: ['Positive', 'Neutral', 'Negative'], default: 'Positive' }
    ]
  }
};
